# Generated by Django 5.2.17 on 2026-09-03 18:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresetArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('streetwear', 'Streetwear & Typographic'), ('minimal', 'Minimalist & Monoline'), ('editorial', 'Editorial & Abstract'), ('vintage', 'Vintage Emblem & Badge')], default='streetwear', max_length=50)),
                ('image', models.ImageField(upload_to='sample_artworks/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('apparel', 'Apparel & Streetwear'), ('headwear', 'Headwear & Caps'), ('accessories', 'Bags & Accessories'), ('drinkware', 'Ceramics & Drinkware')], default='apparel', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('base_color', models.CharField(default='#1E2022', max_length=50)),
                ('color_name', models.CharField(default='Vintage Washed Black', max_length=50)),
                ('material', models.CharField(default='100% Ring-Spun Cotton (240 GSM)', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=38.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Custom Artwork', max_length=200)),
                ('image', models.ImageField(upload_to='user_designs/')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAngle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle_type', models.CharField(choices=[('front', 'Front Perspective'), ('back', 'Back Perspective'), ('side', 'Side / Sleeve Perspective'), ('folded', 'Folded Studio Flatlay')], default='front', max_length=30)),
                ('name', models.CharField(help_text='e.g., Front Chest View', max_length=100)),
                ('base_image', models.ImageField(upload_to='base_products/')),
                ('displacement_map', models.ImageField(blank=True, null=True, upload_to='base_products/displacement/')),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angles', to='customizer.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomizationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Primary Print Zone', max_length=100)),
                ('max_width_mm', models.FloatField(default=350.0, help_text='Print bed width in millimeters')),
                ('max_height_mm', models.FloatField(default=450.0, help_text='Print bed height in millimeters')),
                ('bounding_left_pct', models.FloatField(default=30.0)),
                ('bounding_top_pct', models.FloatField(default=26.0)),
                ('bounding_width_pct', models.FloatField(default=40.0)),
                ('bounding_height_pct', models.FloatField(default=48.0)),
                ('quad_points_json', models.TextField(default='[[30.0, 26.0], [70.0, 26.0], [70.0, 74.0], [30.0, 74.0]]', help_text='JSON array of 4 perspective corner points (top-left, top-right, bottom-right, bottom-left)')),
                ('displacement_strength', models.FloatField(default=16.0, help_text='Fold and wrinkle deformation intensity')),
                ('texture_depth', models.FloatField(default=1.3, help_text='Shadow and highlight texture contrast multiplier')),
                ('blend_mode', models.CharField(choices=[('MULTIPLY', 'Photometric Multiply (Natural Shadow Pass)'), ('OVERLAY', 'Photometric Overlay (Contrast Preservation)'), ('SOFT_LIGHT', 'Soft Light (Subtle Texture Infusion)'), ('NORMAL', 'Standard Alpha Composite')], default='MULTIPLY', max_length=20)),
                ('angle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customization_area', to='customizer.productangle')),
            ],
        ),
        migrations.CreateModel(
            name='MockupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('scale', models.FloatField(default=1.0)),
                ('rotation', models.FloatField(default=0.0)),
                ('offset_x', models.FloatField(default=0.0)),
                ('offset_y', models.FloatField(default=0.0)),
                ('blend_mode', models.CharField(default='MULTIPLY', max_length=20)),
                ('displacement_intensity', models.FloatField(default=16.0)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued in Worker Pipeline'), ('PROCESSING', 'Processing OpenCV Conformation'), ('COMPLETED', 'Render Complete'), ('FAILED', 'Rendering Failed')], default='QUEUED', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('status_message', models.CharField(default='Job initialized', max_length=255)),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='rendered_mockups/')),
                ('execution_time_seconds', models.FloatField(default=0.0)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_angle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mockup_jobs', to='customizer.productangle')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customizer.userdesign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
